### ISSUE TITLE
FEM driver with symmetric matrix storage not working

### ISSUE THREAD

**Issue by fverdugo** [gridap/GridapPardiso.jl#15]
Hi @victorsndvg,

I have realized that the Pardiso solvers are not working properly for symmetric matrices. 

I have used a symmetric matrix in the femdriver, and the tests do not pass. See here:

https://github.com/gridap/GridapPardiso.jl/blob/sym_storage_not_working/test/femdriver.jl

Can you try to fix it?

Thanks!

**Comment by victorsndvg** [comment]
HI @fverdugo ,

this is not a bug. As we decided during implementation, PardisoSolver contains a member variable specifying the matrix type. By default the matrix type is `MTYPE_REAL_NON_SYMMETRIC`, you have to specify a different matrix type during solver creation if you need.

Commit https://github.com/gridap/GridapPardiso.jl/commit/282900c6836dbd56eac5f9a81dc1654e4da3d951 fix the test.

do you agree? Is this the expected behaviour?

**Comment by fverdugo** [comment]
Now I see it. It is the expected behavior! Sorry!

Just two possible improvements:

- It would be nicer to have an informative error message in these situations.
- It would be nice to have a transparent way of creating the `PardisoSolver`, for instance from the Gridap matrix type, the FE operator or the assembler.

For example. In our case, one could write

```julia
op = AffineFEOperator(SymSparseMatrixCSR{1,Float64,Int},V,U,t_Ω)
ls = PardisoSolver(op)
solver = LinearFESolver(ls)
uh = solve(solver,op)
```

instead of

```julia
op = AffineFEOperator(SymSparseMatrixCSR{1,Float64,Int},V,U,t_Ω)
ls = PardisoSolver(GridapPardiso.MTYPE_REAL_SYMMETRIC_INDEFINITE)
solver = LinearFESolver(ls)
uh = solve(solver,op)
```

It should be easy to add this behavior. What do you think?

BTW, in this case the matrix is symmetric positive definite. This info has to be provided by the user. It cannot be taken from the fe operator. In this example the proper way to go is

```julia
op = AffineFEOperator(SymSparseMatrixCSR{1,Float64,Int},V,U,t_Ω)
ls = PardisoSolver(GridapPardiso.MTYPE_REAL_SYMMETRIC_POSITIVE_DEFINITE)
solver = LinearFESolver(ls)
uh = solve(solver,op)
```

**Comment by victorsndvg** [comment]
Ok, It should be easy to perform these modifications :+1: let's go!

**Comment by fverdugo** [comment]
Perfect!

The core functionality we need is to add a `PardisoSolver` constructor from a matrix type (i.e., `SparseMatrixCSC`, `SparseMatrixCSR`, `SymSparseMatrixCSR` ) that chooses default solver parameters for this matrix type.

Then, we can add a new function to the FEOperator interface called `get_matrix_type` (for the moment implement this in this repo for `AffineFEOperator` and `FEOperatorFromTerms`, we will move later to Gridap).

With the two functions you can implement a `PardisoSolver(op::FEOperator)` constructor like
```julia
 PardisoSolver(op::FEOperator) = PardisoSolver(get_matrix_type(op))
```
