### ISSUE TITLE
pardiso iparm Parameter cannot be customized at the driver level

### ISSUE THREAD

**Issue by ericneiva** [gridap/GridapPardiso.jl#36]
Hello there,

I am using the latest Intel® oneAPI MKL version 2022.

I have found that the call to `pardisoinit!` at the `symbolic setup` [here](https://github.com/gridap/GridapPardiso.jl/blob/af70c13a95fc602be06c29c1865e0dc234bb2b52/src/LinearSolver.jl#L126) overwrites the `iparm` provided by the user with the default values for the matrix at hand.

According to `pardisoinit!` [documentation](https://www.intel.com/content/www/us/en/develop/documentation/onemkl-developer-reference-c/top/sparse-solver-routines/onemkl-pardiso-parallel-direct-sparse-solver-iface/pardisoinit.html):

> The recommended way is to avoid using pardisoinit and to initialize pt and set the values of the iparm array manually as the default parameters might not be the best for a particular use case.
> An alternative method to set default iparm values is to call pardiso in the analysis phase with iparm(1)=0. In this case, the solver handle pt must be initialized with zero values.

But we cannot easily remove the call to `pardisoinit!` and let the analysis phase fill the default iparm, because our iparm is, actually, non-default, in general. The reason is we use it to dispatch on the indexing type before the analysis phase, see [here](https://github.com/gridap/GridapPardiso.jl/blob/af70c13a95fc602be06c29c1865e0dc234bb2b52/src/LinearSolver.jl#L129).

Any ideas on how to tackle this?

Maybe @fverdugo we can address this when we (video)meet again and agree then on a fix.

**Comment by fverdugo** [comment]
Good point @ericneiva !

another option is not calling pardisoinit internally at all if the user provides the iparm. I.e., assume that if the user provides iparm he/she is expert enough to provide it in a valid fully initialized state. This can be done by the user e.g., by calling pardisoinit! explicitly before setting extra custom parameters.
