### ISSUE TITLE
Reusing Symbolic Setup

### ISSUE THREAD

**Issue by ianmatthewhammond** [gridap/GridapPardiso.jl#38]
Hi all,

I appear to not be able to reuse the symbolic factorization when performing the numerical factorization on two different matrices of the same sparsity pattern. I think I've narrowed down why in LinearSolver.jl for GridapPardiso:

https://github.com/gridap/GridapPardiso.jl/blob/5d893b1352295228a07eba4d89e734f6e65212cf/src/LinearSolver.jl#L199-L204

On line 204, the variable `mat` is reassigned to be the matrix belonging to the symbolic setup. Thus, the argument passed into the function is never used, and all future matrices passed into numerical setups are ignored.

**Comment by fverdugo** [comment]
Hi @hammy4815,

Thanks for reporting this. It looks like a bug.

Can you try to comment out line 204 and see if it solves your problem?

**Comment by ianmatthewhammond** [comment]
> Can you try to comment out line 204 and see if it solves your problem?

Yep, commenting out that line solved my problem.

**Comment by fverdugo** [comment]
Perfect!

feel free to open a PR with the fix.
