### ISSUE TITLE
Split tests in several @testsets

### ISSUE THREAD

**Issue by fverdugo** [gridap/GridapPardiso.jl#6]
We need to structure the tests a little bit. Move the implementation of the tests in separate files (defining one new module each), and then include them in `runtests.jl` using the @testset macro.

**Comment by victorsndvg** [comment]
fixed in f044040..ccca42b

**Comment by fverdugo** [comment]
@victorsndvg the changes need to be merged into master.

I reopen the issue, once they are in master, you can close it.

**Comment by victorsndvg** [comment]
merged in 4f2669d13aba742877ae104cea7387ed94ae052c
