### ISSUE TITLE
Register the package in Julia General

### ISSUE THREAD

**Issue by fverdugo** [gridap/GridapPardiso.jl#7]
Follow the instructions [here](https://github.com/gridap/Gridap.jl/wiki/How-to-register-a-julia-package)

**Comment by victorsndvg** [comment]
merged in 4f2669d13aba742877ae104cea7387ed94ae052c

**Comment by victorsndvg** [comment]
Finally done in  d0e462f2754ce179edaa8776dc1f31a8df0f59b2
